AWSTemplateFormatVersion: "2010-09-09"
Metadata:
  
Description: "Time Stream for UBI"
Resources:
    TimestreamDatabase:
        Type: "AWS::Timestream::Database"
        Properties:
            DatabaseName: "ei_out"
            KmsKeyId: !Sub "arn:aws:kms:${AWS::Region}:${AWS::AccountId}:key/yourkey here"
            MagneticStoreWriteProperties: MagneticStoreWriteProperties
               EnableMagneticStoreWrites: true
               MagneticStoreRejectedDataLocation:
                S3Configuration:
                  BucketName: "testbucket"
                  EncryptionOption: "SSE_KMS"
                  KmsKeyId: "1234abcd-12ab-34cd-56ef-1234567890ab"
                  ObjectKeyPrefix: "prefix"


Type: AWS::Timestream::Table
DependsOn: "ei_out"
Properties:
    TableName: "table1"
    DatabaseName: "ei_out"
    RetentionProperties:
        MemoryStoreRetentionPeriodInHours: "24"
        MagneticStoreRetentionPeriodInDays: "7"
